In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np


In [8]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
arr2[5:15]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
pip install pandas

In [15]:
import pandas as pd 
ser1 = pd. Series ([1,2,3],index = ["Oranges","Bananas","Apples"])
ser1
                          

Oranges    1
Bananas    2
Apples     3
dtype: int64

In [55]:
ser1["pears"] = 4
ser1

Oranges    1
Bananas    2
Apples     3
pears      4
dtype: object

In [77]:
ser2 = pd.DataFrame({'Name':["Mathew","Diphu","Mary","Abhirami","Vishnu","Abhul","Nishad","Christy","Megha","Ashiq"],'Age':
                               [34,32,35,24,26,27,31,30,20,23], 'Gender':
                               ["Male","Male","Female","Female","Male","Male","Male","Female","Female","Male"]}, index = [1,2,3,4,5,6,7,8,9,10], 
                    columns = ['Name','Age','Gender'])
ser2

Name  Age  Gender
1     Mathew   34    Male
2      Diphu   32    Male
3       Mary   35  Female
4   Abhirami   24  Female
5     Vishnu   26    Male
6      Abhul   27    Male
7     Nishad   31    Male
8    Christy   30  Female
9      Megha   20  Female
10     Ashiq   23    Male

In [79]:
ser2["Occupation"] = ["Programmer","programmer","Analyst","Manager","Analyst","Programmer","Analyst","manager","Programmer","Analsyt"]
ser2

Name  Age  Gender  Occupation
1     Mathew   34    Male  Programmer
2      Diphu   32    Male  programmer
3       Mary   35  Female     Analyst
4   Abhirami   24  Female     Manager
5     Vishnu   26    Male     Analyst
6      Abhul   27    Male  Programmer
7     Nishad   31    Male     Analyst
8    Christy   30  Female     manager
9      Megha   20  Female  Programmer
10     Ashiq   23    Male     Analsyt

In [89]:
ser2["Age"] > 30

1      True
2      True
3      True
4     False
5     False
6     False
7      True
8     False
9     False
10    False
Name: Age, dtype: bool

In [97]:
ser2.to_csv('Python assignment 7.csv')
